
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package analizadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MENOS = 4;
  public static final int MENOR = 6;
  public static final int PUNTO = 13;
  public static final int CADENA = 23;
  public static final int DOSPUNTOS = 12;
  public static final int CDOBLE = 20;
  public static final int SALTOL = 18;
  public static final int DOBLEPORC = 11;
  public static final int PREG = 17;
  public static final int ID = 21;
  public static final int POR = 15;
  public static final int CSIMPLE = 19;
  public static final int LLAVECIERRE = 10;
  public static final int COMA = 7;
  public static final int MAYOR = 5;
  public static final int EOF = 0;
  public static final int CONJ = 2;
  public static final int error = 1;
  public static final int DISY = 14;
  public static final int LISTA = 8;
  public static final int MAS = 16;
  public static final int INTERVALO = 22;
  public static final int LLAVEABRE = 9;
  public static final int PTCOMA = 3;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "CONJ",
  "PTCOMA",
  "MENOS",
  "MAYOR",
  "MENOR",
  "COMA",
  "LISTA",
  "LLAVEABRE",
  "LLAVECIERRE",
  "DOBLEPORC",
  "DOSPUNTOS",
  "PUNTO",
  "DISY",
  "POR",
  "MAS",
  "PREG",
  "SALTOL",
  "CSIMPLE",
  "CDOBLE",
  "ID",
  "INTERVALO",
  "CADENA"
  };
}

